Lang PT-BR
XFox111/PasswordGeneratorExtension pull request #70
Opened 2022-11-10 15:22 UTC by maisondasilva

## Description
> add Lang Portuguese Brazil pt_Br

2022-11-17 20:02 UTC, XFox111 reviewed
Hi, thanks for your contribution!
Your PR seems good. I'll include it into next Patch Tuesday update

Please update PR description, so it contains summary of the proposed changes

Also, please send me Brazilian Portuguese translation for the following text. It will go into description section on the store page

```text
Extension for web browsers which helps you to easily generate strong passwords in one click

# Features
- Create strong passwords in one click
- Customizable generator
- Clean and simple UI
- Dark mode

# Hey, It's open-source software!
If you know how to improve this extension you can check its GitHub Repository
Check out release changelog
```

---
One more thing. As described in [Contribution Guidelines](https://github.com/XFox111/PasswordGeneratorExtension/blob/main/CONTRIBUTING.md#contributing-to-translations), next time you want to start working on a pull request, make sure you've been assigned for an issue:

> Note that whatever you want to contribute to the codebase, you should do it only after you got assigned on an issue

It is vital to show that you are working on the issue, so other people don't start working on it too

2022-11-17 20:08 UTC, maisondasilva commented
```
Extensão para navegadores da web que ajuda você a gerar facilmente senhas fortes com um clique

# Características
- Crie senhas fortes com um clique
- Gerador personalizável
- UI limpa e simples
- Modo escuro

# Ei, é um software de código aberto!
Se você sabe como melhorar esta extensão, você pode verificar seu repositório GitHub
Confira o changelog da versão
```

2022-11-17 20:56 UTC, XFox111 submitted a review, later dismissed

2022-11-29 22:30 UTC, maisondasilva commented
Change pt-br for pt_BR

2022-11-30 20:43 UTC, XFox111 commented
> Change pt-br for pt_BR

Oh, yeah. It indeed should be `pt_BR`. Guess, I need to make better reviews 😅

2022-11-30 22:21 UTC, XFox111 commented
@maisondasilva yeah, sure. I'll just come back to it a bit later

2022-12-02 20:26 UTC, XFox111 requested changes
Yep. I had to be tested first. I've found a line that you missed :)

2022-12-02 20:26 UTC, XFox111 commented on public/_locales/pt_BR/messages.json
> +		"message": "Generate password without special symbols",
I think, it should be translated as well

2022-12-06 12:12 UTC, XFox111 approved these changes
Ok, I think it's good to go!
Thanks for your contribution :)

2022-12-06 12:18 UTC, merged

2022-12-06 14:01 UTC, XFox111 commented
Jeez. Looks like I need a break. Sorry, I messed up usernames and put another person. Fixed it now 😅

2022-12-06 14:22 UTC, maisondasilva commented
I asked because I didn't see him in this translation, no problem and good rest 😂😂😅😅

2022-12-12 02:24 UTC, maisondasilva commented
@XFox111 Repeating is Is there an option to exclude repeated passwords, that is, passwords that have already been generated and prevent it from being generated again, correct?

![image](https://user-images.githubusercontent.com/11423362/206947544-c5d8dbc0-e32a-45dd-85ef-196e9ef80276.png)

2022-12-12 14:46 UTC, XFox111 commented
> @XFox111 "Repeating" is Is there an option to exclude repeated passwords, that is, passwords that have already been generated and prevent it from being generated again, correct?

I'm not sure if I understand your question correctly. The "Repeating" option goes under "Character options -> Exclude" section. So, it prevents characters that already has been added to the password from being added again (every character in generated password becomes unique)